import '../../models/property_model.dart';
import '../../models/user_model.dart';

class DemoData {
  static final demoUser = UserModel(
    uid: 'demo_user_123',
    email: 'demo@estatekart.com',
    displayName: 'Demo User',
    role: 'seller',
    photoUrl: 'https://i.pravatar.cc/150?u=demo',
    phone: '+91 98765 43210',
    isVerified: true,
    subscriptionPlan: 'pro',
    createdAt: DateTime.now().toIso8601String(),
    wishlist: ['prop_1', 'prop_3'],
    recentlyViewed: ['prop_2'],
  );

  static final List<PropertyModel> properties = [
    PropertyModel(
      id: 'prop_1',
      title: 'Skyline Luxury Apartment',
      description: 'Experience luxury living in this spacious 3 BHK apartment with a breathtaking view of the city skyline. Features high-end finishes, Italian marble flooring, and a modular kitchen.',
      price: 25000000,
      priceUnit: 'total',
      type: 'Apartment',
      purpose: 'Buy',
      status: 'ready_to_move',
      bhk: 3,
      area: 1850,
      areaUnit: 'sqft',
      city: 'Mumbai',
      locality: 'Bandra West',
      address: 'Skyline Towers, Hill Road, Bandra West, Mumbai, Maharashtra',
      images: [
        'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800',
        'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800',
      ],
      videos: [],
      amenities: ['Swimming Pool', 'Gym', 'Parking', 'Security'],
      sellerId: 'seller_1',
      sellerName: 'Elite Realty',
      sellerPhone: '9876543210',
      isVerified: true,
      isFeatured: true,
      createdAt: DateTime.now().subtract(const Duration(days: 2)).toIso8601String(),
    ),
    PropertyModel(
      id: 'prop_2',
      title: 'Green Valley Villa',
      description: 'Beautiful 4 BHK independent villa surrounded by lush greenery. Private garden, swimming pool, and double height ceiling in the living room.',
      price: 45000000,
      priceUnit: 'total',
      type: 'Villa',
      purpose: 'Buy',
      status: 'under_construction',
      bhk: 4,
      area: 3200,
      areaUnit: 'sqft',
      city: 'Bengaluru',
      locality: 'Whitefield',
      address: 'Green Valley Estates, Whitefield, Bengaluru, Karnataka',
      images: [
        'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=800',
      ],
      videos: [],
      amenities: ['Private Pool', 'Garden', 'Club House', 'Power Backup'],
      sellerId: 'seller_2',
      sellerName: 'Adarsh Builders',
      sellerPhone: '9876543211',
      isVerified: true,
      isFeatured: true,
      createdAt: DateTime.now().subtract(const Duration(days: 5)).toIso8601String(),
    ),
    PropertyModel(
      id: 'prop_3',
      title: 'Modern Studio in Tech Park',
      description: 'Compact and functional studio apartment perfect for working professionals. Fully furnished and walking distance to major IT parks.',
      price: 25000,
      priceUnit: 'per_month',
      type: 'Apartment',
      purpose: 'Rent',
      status: 'ready_to_move',
      bhk: 1,
      area: 450,
      areaUnit: 'sqft',
      city: 'Hyderabad',
      locality: 'Hitech City',
      address: 'Tech Hub Apartments, Hitech City, Hyderabad, Telangana',
      images: [
        'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800',
      ],
      videos: [],
      amenities: ['Gym', 'Lift', 'Security', 'Internet'],
      sellerId: 'seller_3',
      sellerName: 'Suresh Kumar',
      sellerPhone: '9876543212',
      isVerified: false,
      isFeatured: false,
      createdAt: DateTime.now().subtract(const Duration(days: 1)).toIso8601String(),
    ),
  ];
}
